# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='bot_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.BotQuestion', verbose_name='\u0412\u043e\u043f\u0440\u043e\u0441 \u0431\u043e\u0442\u0430'),
        ),
    ]
