# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_siteconfiguration_block_trap_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='google_maps_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='\u0410\u0434\u0440\u0435\u0441 \u043d\u0430 \u043a\u0430\u0440\u0442\u0435'),
        ),
    ]
