# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-11 08:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_siteconfiguration_google_maps_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='show_team',
        ),
    ]
