# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_auto_20170717_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='block_trap_text',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='about_slogan_text',
            field=models.TextField(blank=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043f\u043e\u0434 \u0441\u043b\u043e\u0433\u0430\u043d\u043e\u043c'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='brand_slogan',
            field=models.CharField(default='Rule the rules', max_length=255, verbose_name='\u0421\u043b\u043e\u0433\u0430\u043d \u043a\u043e\u043c\u043f\u0430\u043d\u0438\u0438'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='trap_block_text_1',
            field=models.TextField(blank=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043f\u0435\u0440\u0432\u043e\u0433\u043e \u0431\u043b\u043e\u043a\u0430-\u043b\u043e\u0432\u0443\u0448\u043a\u0438'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='trap_block_text_2',
            field=models.TextField(blank=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0432\u0442\u043e\u0440\u043e\u0433\u043e \u0431\u043b\u043e\u043a\u0430-\u043b\u043e\u0432\u0443\u0448\u043a\u0438'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='trap_block_text_3',
            field=models.TextField(blank=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0442\u0440\u0435\u0442\u044c\u0435\u0433\u043e \u0431\u043b\u043e\u043a\u0430-\u043b\u043e\u0432\u0443\u0448\u043a\u0438'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='trap_block_text_4',
            field=models.TextField(blank=True, verbose_name='\u0422\u0435\u043a\u0441\u0442 \u0447\u0435\u0442\u0432\u0435\u0440\u0442\u043e\u0433\u043e \u0431\u043b\u043e\u043a\u0430-\u043b\u043e\u0432\u0443\u0448\u043a\u0438'),
        ),
    ]
