# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 15:14
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_type', models.CharField(choices=[('positive', '\u041f\u043e\u0437\u0438\u0442\u0438\u0432\u043d\u044b\u0439'), ('reject', '\u041e\u0442\u043a\u0430\u0437\u043d\u043e\u0439')], default='positive', max_length=20, verbose_name='\u0422\u0438\u043f \u043e\u0442\u0432\u0435\u0442\u0430')),
                ('title', models.CharField(max_length=255, verbose_name='\u041e\u0442\u0432\u0435\u0442')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u043e\u0442\u0432\u0435\u0442\u0430')),
            ],
            options={
                'verbose_name': '\u041e\u0442\u0432\u0435\u0442',
                'verbose_name_plural': '\u041e\u0442\u0432\u0435\u0442\u044b',
            },
        ),
        migrations.CreateModel(
            name='BotPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='\u0418\u043c\u044f \u043f\u0435\u0440\u0441\u043e\u043d\u0430\u0436\u0430')),
                ('greeting', models.TextField(verbose_name='\u0422\u0435\u043a\u0441\u0442 \u043f\u0440\u0438\u0432\u0435\u0442\u0441\u0442\u0432\u0438\u044f')),
            ],
            options={
                'verbose_name': '\u041f\u0435\u0440\u0441\u043e\u043d\u0430\u0436',
                'verbose_name_plural': '\u041f\u0435\u0440\u0441\u043e\u043d\u0430\u0436\u0438',
            },
        ),
        migrations.CreateModel(
            name='BotQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u0412\u043e\u043f\u0440\u043e\u0441')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.BotPerson', verbose_name='\u041f\u0435\u0440\u0441\u043e\u043d\u0430\u0436')),
            ],
            options={
                'verbose_name': '\u0412\u043e\u043f\u0440\u043e\u0441',
                'verbose_name_plural': '\u0412\u043e\u043f\u0440\u043e\u0441\u044b',
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u0418\u043c\u044f \u043a\u043b\u0438\u0435\u043d\u0442\u0430')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail \u043a\u043b\u0438\u0435\u043d\u0442\u0430')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='\u0414\u0430\u0442\u0430 \u043e\u0442\u0432\u0435\u0442\u0430')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.BotAnswer', verbose_name='\u041e\u0442\u0432\u0435\u0442')),
            ],
            options={
                'verbose_name': '\u041e\u0442\u0432\u0435\u0442 \u043a\u043b\u0438\u0435\u043d\u0442\u0430',
                'verbose_name_plural': '\u041e\u0442\u0432\u0435\u0442\u044b \u043a\u043b\u0438\u0435\u043d\u0442\u043e\u0432',
            },
        ),
        migrations.AddField(
            model_name='botanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='bot.BotQuestion', verbose_name='\u0412\u043e\u043f\u0440\u043e\u0441'),
        ),
    ]
