# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_menuitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnruledNumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='\u0417\u043d\u0430\u0447\u0435\u043d\u0438\u0435')),
                ('measure_unit', models.CharField(max_length=120, verbose_name='\u0415\u0434\u0438\u043d\u0438\u0446\u0430 \u0438\u0437\u043c\u0435\u0440\u0435\u043d\u0438\u044f')),
            ],
            options={
                'verbose_name': 'Unruled \u0432 \u0446\u0438\u0444\u0440\u0430\u0445',
                'verbose_name_plural': 'Unruled \u0432 \u0446\u0438\u0444\u0440\u0430\u0445',
            },
        ),
    ]
