# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_whyunruled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ('-release_date',), 'verbose_name': '\u041f\u043e\u0440\u0442\u0444\u043e\u043b\u0438\u043e', 'verbose_name_plural': '\u041f\u043e\u0440\u0442\u0444\u043e\u043b\u0438\u043e'},
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(default='/img/not-found.png', upload_to='portfolio', verbose_name='\u0421\u043a\u0440\u0438\u043d\u0448\u043e\u0442'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='\u0421\u0441\u044b\u043b\u043a\u0430 \u043d\u0430 \u0441\u0430\u0439\u0442'),
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio', verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.Portfolio', verbose_name='\u041f\u043e\u0440\u0442\u0444\u043e\u043b\u0438\u043e')),
            ],
            options={
                'verbose_name': '\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0433\u0430\u043b\u0435\u0440\u0435\u0438 \u043f\u043e\u0440\u0442\u0444\u043e\u043b\u0438\u043e',
                'verbose_name_plural': '\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u044f \u0433\u0430\u043b\u0435\u0440\u0435\u0438 \u043f\u043e\u0440\u0442\u0444\u043e\u043b\u0438\u043e',
            },
        ),
    ]
