# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-11 07:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
