# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-11 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_delete_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='position',
            field=models.CharField(choices=[('header', 'Header'), ('footer', 'Footer')], default='header', max_length=10, verbose_name='\u041f\u043e\u043b\u043e\u0436\u0435\u043d\u0438\u0435'),
        ),
    ]
