# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 10:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_auto_20170711_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Portfolio', verbose_name='\u041f\u043e\u0440\u0442\u0444\u043e\u043b\u0438\u043e'),
        ),
    ]
