# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 11:52
from __future__ import unicode_literals

from django.db import migrations


def preset_order(apps, schema_editor):
    order = 0
    model = apps.get_model('content', 'MenuItem')
    for obj in model.objects.all():
        order += 1
        obj.order = order
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_auto_20170718_1144'),
    ]

    operations = [
        migrations.RunPython(preset_order),
    ]
